apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
  labels:
    app: stanbic-getting-started
    app.kubernetes.io/component: web
    app.kubernetes.io/instance: stanbic-getting-started
    app.kubernetes.io/name: stanbic-getting-started
    app.kubernetes.io/part-of: stanbic-getting-started
    app.openshift.io/runtime: java
  name: stanbic-getting-started
spec:
  replicas: 1
  selector:
    matchLabels:
      app: stanbic-getting-started
  template:
    metadata:
      labels:
        app: stanbic-getting-started
    spec:
      containers:
      - name: stanbic-getting-started
        imagePullPolicy: Always
        image: quay.io/anmir78/stanbic-getting-started:latest
        livenessProbe:
          failureThreshold: 3
          httpGet:
            path: /
            port: 8080
            scheme: HTTP
          initialDelaySeconds: 45
          periodSeconds: 10
          successThreshold: 1
          timeoutSeconds: 1
        ports:
        - containerPort: 8080
          protocol: TCP
        - containerPort: 8443
          protocol: TCP
        - containerPort: 8778
          protocol: TCP
        readinessProbe:
          failureThreshold: 3
          httpGet:
            path: /
            port: 8080
            scheme: HTTP
          initialDelaySeconds: 45
          periodSeconds: 10
          successThreshold: 1
          timeoutSeconds: 5
